# Generated by Django 2.1.2 on 2019-01-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190104_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_row_count',
            field=models.IntegerField(default=0),
        ),
    ]
