# Generated by Django 2.1.2 on 2019-01-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190104_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_row_count',
        ),
    ]
