# Generated by Django 2.1.2 on 2019-01-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_document_file_row_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_seperator',
        ),
    ]
