# Generated by Django 2.1.2 on 2019-01-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_document_file_seperator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_seperator',
            field=models.CharField(default=',', max_length=10),
        ),
    ]
