# Generated by Django 2.1.2 on 2019-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_document_file_seperator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_row_count',
            field=models.IntegerField(default=0),
        ),
    ]
