# Generated by Django 2.1.2 on 2019-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_document_file_row_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_row_count',
            new_name='row_count',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_seperator',
            new_name='seperator',
        ),
        migrations.AddField(
            model_name='document',
            name='encoding',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='header_row',
            field=models.IntegerField(default=0),
        ),
    ]
