# Generated by Django 2.1.2 on 2019-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190104_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.IntegerField(default=0),
        ),
    ]
