# Generated by Django 2.1.2 on 2019-01-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_document_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=20),
        ),
    ]
