# Generated by Django 2.1.2 on 2019-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190104_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('sample_path', models.CharField(blank=True, max_length=255)),
                ('selected_models', models.CharField(blank=True, max_length=255)),
                ('auc', models.CharField(blank=True, max_length=255)),
                ('logloss', models.CharField(blank=True, max_length=255)),
                ('mean_per_class_error', models.CharField(blank=True, max_length=255)),
                ('rmse', models.CharField(blank=True, max_length=255)),
                ('mse', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
