# Generated by Django 2.1.2 on 2019-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_modeldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='port',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
