# Generated by Django 2.1.2 on 2019-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_modeldata_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='ip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
