# Generated by Django 2.1.2 on 2019-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_modeldata_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
