# Generated by Django 2.2.2 on 2019-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_modeldata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
