# Generated by Django 2.2.2 on 2019-08-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_document_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='url',
            new_name='document_url',
        ),
    ]
