# Generated by Django 2.2.4 on 2019-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190805_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('query_status', models.BooleanField(default=False)),
                ('runned_by', models.CharField(default='', max_length=255)),
                ('query_startdate', models.DateTimeField(auto_now_add=True)),
                ('query_enddate', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.CharField(blank=True, max_length=255)),
                ('pickle_file', models.CharField(blank=True, max_length=255)),
                ('document_pk', models.IntegerField(default=0)),
                ('prev_trans_pk', models.IntegerField()),
            ],
        ),
    ]
